# Simple pre-commit workflow - alternative to the comprehensive quality-check.yml
# You can use this if you want just the basic pre-commit checks without extra security scans
name: Pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck hadolint

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          npm install -g prettier

      - name: Cache pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # For PRs, run only on changed files
            pre-commit run --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }}
          else
            # For pushes to main/develop, run on all files
            pre-commit run --all-files
          fi
